Add unit test for API endpoints using TestClient library from fast-api
VallariAg/teuthology-api pull request #13
Opened 2023-03-14 15:24 UTC by Dorcas-BD

Added unit tests for API endpoints using FastAPI's TestClient library to ensure correct responses and improve application quality. Used TestClient to make HTTP requests, wrote test functions for various use cases and checked for correct status codes, headers, and response bodies. Please review @amathuria @kamoltat @zmc

2023-03-20 15:43 UTC, kamoltat requested changes
Please also add a unit-test for 1 func in src/services/kill.py

2023-03-20 16:51 UTC, Dorcas-BD commented
> Please also add a unit-test for 1 func in src/services/kill.py

Alright, I will do that @kamoltat

2023-03-24 23:26 UTC, Dorcas-BD commented
Hello @kamoltat, I wanted to let you know that I've added unit tests for src/services/kill.py and signed my commit. I have a question: Do I need to open a new pull request to tag the "gsoc-outreachy" label, or can I do it on this pull request?

2023-03-26 16:52 UTC, Dorcas-BD commented
Hello @kamoltat,

I have pushed a commit for my Task 3. Please review it and provide me with your feedback or suggestions. Additionally, if you haven't had a chance to review my Task 2 yet, please also look at that.

Thank you in advance for your help.

cc: @amathuria @zmc

2026-06-01 16:45 UTC, closed without merging